[workspace]
resolver = "2"
members = [
    "wallet",
]
exclude = ["examples"]

[workspace.package]
authors = ["Bitcoin Dev Kit Developers"]

[workspace.lints.clippy]
print_stdout = "deny"
print_stderr = "deny"
